### ISSUE TITLE
Add documentation: How to prepare graphdb for reverse proxy

### ISSUE THREAD

**Issue by jagerda** [ejp-rd-vp/FiaB#2]
# problem
accessing graphdb through a reverse proxy on a custom path can mess up the entire graphdb-ui if you haven't prepared graphdb for that. Example: Here, graphdb is accessed through a apache2 reverse proxy on the path /graphdb-ctsr
![grafik](https://user-images.githubusercontent.com/95087241/212358299-5a65c8d2-5753-422c-97ef-ef918be2d49c.png)

# solution
In any case (a or b): For a production-setup, you must of course put in the real URI (not localhost) and https instead of http

a) when using the ontotext-image and docker-compose like it's done e.g. in FAIR-ready-to-go-folder, then you need to configure `Dgraphdb.external-url` in the CMD that will be executed in the container, e.g. like this:
```
  graphdb:
    image: ontotext/graphdb:10.1.2
    restart: always
    hostname: graphdb-ctsr
    command: ["-Dgraphdb.home=/opt/graphdb/home -Dgraphdb.external-url=http://localhost/graphdb-ctsr"]
    ports:
      - 7201:7200
    volumes:
      - fair-data-point-ctsr:/opt/graphdb/home
    networks:
      - default
```
b) when using a Dockerfile to build a local graphdb-image based on a graphdb-zip then within the Dockerfile you need to 
replace the </br> `CMD ["-Dgraphdb.home=/opt/graphdb/home"]` </br> with something like </br>`CMD ["-Dgraphdb.home=/opt/graphdb/home -Dgraphdb.external-url=http://localhost/graphdb-ctsr"]`
