### ISSUE TITLE
markw/yarrrml-rml-ejp:0.1.1 Docker malfunction

### ISSUE THREAD

**Issue by pabloalarconm** [ejp-rd-vp/FiaB#21]
Hello,

I tested how `markw/yarrrml-rml-ejp:0.1.1` behaves using `CARE.csv` and `CARE_yarrrml.yaml` and executing the transformation triggering `http://127.0.0.1:4567/CARE`. Some weird cases happened:

1) some of the temporary files from`tmp` were not removed, such as `CARE_part_1.csv` and  `CARE_part_1.csv.nq`.
2) resulting data from the `triples` folder was created as `CARE.nq` but It was only a fraction of the whole expected RDF, apparently identical to `CARE_part_1.csv.nq`.
3) Source data from `CARE.csv` has been replaced by the content of `CARE_part_1.csv`, losing the original data.

`CARE.csv` file used: https://github.com/CARE-SM/CARE-SM-Toolkit/blob/main/toolkit/API/data/CARE.csv

`CARE_yarrrml.yaml` file used: https://github.com/CARE-SM/CARE-SM-Implementation/blob/main/YARRRML/CARE_yarrrml.yaml

Docker compose used:

```yaml
version: "3"
services:
  yarrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.1.1
    container_name: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
    ports:
      - "4567:4567"
    volumes:
      - ./data:/mnt/data

```
Bests,
@pabloalarconm
